management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0

jdbc:
  churierpweb:
    driver: org.postgresql.Driver

server:
  port: 7080

spring:
  datasource:
    url: jdbc:postgresql://localhost:6960/churiservices_orders
    username: churiservices_orders
    password: angel7
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8000/auth/realms/ChuriservicesRealm/protocol/openid-connect/certs
# cloud:
#   consul:
#     discovery:
#       service-name: churiservices-orders
#       instance-id: churiservices-orders
#       enabled: true
#       register: true
#       prefer-ip-address: true
#       register-health-check: true
#       prefer-agent-address: true
#       health-check-url: http://localhost:${server.port}/ping
#       health-check-interval: 10s
#     config:
#       fail-fast: true
#       import-check:
#         enabled: false
#     host: localhost
#     port: 8500
#   application:
#     name: churiservices-orders


#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

#spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect

org:
  bastanchu:
    churiservices:
      executionMode: real
      timestampFormat: yyyy-MM-dd HH:mm:ss Z
      system:
        baseTokenURL: http://localhost:8000/auth/realms/ChuriservicesRealm//protocol/openid-connect/token
      rabbitmq:
        exchanges:
          orders: org.bastanchu.churiservices.orders.ordersExchange
        queues:
          orderstodeliveries: org.bastanchu.churiservices.orders.orderstodeliveriesQueue
        routingkeys:
          orderstodeliveries: org.bastanchu.churiservices.orders.orderstodeliveriesRoutingKey
      orders:
        systemName: churiservices-orders
        systemVersion: @project.version@
        dbSystemName: churiservices-orders-db
      articles:
        baseURL: http://localhost:7081/