version: '3'
services:
  #--CHURISERVICES--
  #ORDERS
  churiservices-orders-db:
    image: postgres:latest
    volumes:
      - churiservices-orders-db-volume:/var/lib/postgresql/data
    ports:
      - ${ORDERS_POSTGRES_DB_OUTER_PORT}:5432
    expose:
      - "5432"
    environment:
      POSTGRES_DB: ${ORDERS_POSTGRES_DB}
      POSTGRES_USER: ${ORDERS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ORDERS_POSTGRES_PASSWORD}
      PGDATA: ${DEFAULT_PGDATA_DIR}
    networks:
      - churisevices-net
  #ARTICLES
  churiservices-articles-db:
    image: postgres:latest
    volumes:
      - churiservices-articles-db-volume:/var/lib/postgresql/data
    ports:
      - ${ARTICLES_POSTGRES_DB_OUTER_PORT}:5432
    expose:
      - "5432"
    environment:
      POSTGRES_DB: ${ARTICLES_POSTGRES_DB}
      POSTGRES_USER: ${ARTICLES_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ARTICLES_POSTGRES_PASSWORD}
      PGDATA: ${DEFAULT_PGDATA_DIR}
    networks:
      - churisevices-net
  # churiservices-articles:
  #   image: articles:1.0-SNAPSHOT
  #   ports:
  #     - 7081:7081
  #   expose:
  #     - "7081"
  #   networks:
  #     - churisevices-net
  #DELIVERIES
  churiservices-deliveries-db:
    image: postgres:latest
    volumes:
      - churiservices-deliveries-db-volume:/var/lib/postgresql/data
    ports:
      - ${DELIVERIES_POSTGRES_DB_OUTER_PORT}:5432
    expose:
      - "5432"
    environment:
      POSTGRES_DB: ${DELIVERIES_POSTGRES_DB}
      POSTGRES_USER: ${DELIVERIES_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DELIVERIES_POSTGRES_PASSWORD}
      PGDATA: ${DEFAULT_PGDATA_DIR}
    networks:
      - churisevices-net
  #--SYSTEM--
  #KEYCLOAK
  churiservices-system-keycloak-db:
    image: postgres:latest
    volumes:
      - churiservices-system-keycloak-db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - churisevices-net
  churiservices-system-keycloak:
    image: bitnami/keycloak:latest
    environment:
      KEYCLOAK_DATABASE_VENDOR: postgresql
      KEYCLOAK_DATABASE_HOST: churiservices-system-keycloak-db
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_SCHEMA: public
      KEYCLOAK_DATABASE_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
      KC_HTTP_RELATIVE_PATH: /auth #Base URL to enter into login screen and all routes
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8000:8080
    expose:
      - "8080"
    depends_on:
      - churiservices-system-keycloak-db
    networks:
      - churisevices-net
  #CONSUL
# churiservices-system-consul:
#   image: hashicorp/consul:1.18
#   ports:
#     - 8500:8500
#   expose:
#     - "8500"
#   networks:
#     - churisevices-net
  #RABBIT MQ
  rabbitmq:
    image: rabbitmq:3.13.3-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ../tmp/rabbitmq/data/:/var/lib/rabbitmq/
      - ../tmp/rabbitmq/log/:/var/log/rabbitmq/
    networks:
      - churisevices-net
  #GRAFANA LOKI
  loki:
    image: grafana/loki:2.9.2
    user: "1000"
    volumes:
      - ./Loki/loki-config.yaml:/etc/loki/local-config.yaml
      - ../tmp/loki:/tmp/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - churisevices-net
  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - churiservices-system-grafana-volume:/var/lib/grafana
    image: grafana/grafana:10.1.10-ubuntu
    ports:
      - "3000:3000"
    networks:
      - churisevices-net
volumes:
  churiservices-orders-db-volume:
  churiservices-articles-db-volume:
  churiservices-deliveries-db-volume:
  churiservices-system-keycloak-db-volume:
  churiservices-system-grafana-volume:
networks:
  churisevices-net:
    driver: bridge
#Execute these steps in the same directory where docker-compose.yaml is
#Step 1 verification
#docker compose config
#Step 2
#docker compose build
#Step 3 to run
#docker compose up -d
#Step 4 to stop
#docker compose down
