apiVersion: v1
kind: Secret
metadata:
  name: storage-sg-valencia-secret
  namespace: devel
type: Opaque
stringData:
  database-name: "sg_valencia"
  database-user: "angel"
  database-password: "angel8"
  create-database.sql: |
    create database sg_valencia;
    create user angel with encrypted password 'angel8';
    alter database sg_valencia owner to angel;
#data:
  #sg-valencia
#  database-name: c2ctdmFsZW5jaWE=
  #angel
#  database-user: YW5nZWw=
  #angel8
#  database-password: YW5nZWw4