package org.bastanchu.churiservices.core.api.model.orders

import io.swagger.v3.oas.annotations.media.Schema
import org.bastanchu.churiservices.core.api.model.addresses.Address
import java.math.BigDecimal

@Schema(name = "OrderHeader",
        description = "Order header structure to serve orders.")
data class OrderHeader(
                       @field:Schema(description = "Order id unique identifier generated by this system",
                                         example = "2716524412" ,
                                        required = false)
                       var orderId : Int = 0,
                       @field:Schema(description = "Convenience identifier provided by order creator to track its order.",
                                         example = "ACV-7365513" ,
                                        required = false)
                       var customerOrderId : String = "",
                       @field:Schema(description = "Customer id responsible for this order (Registered under customers system).",
                                         example = "00018122232" ,
                                        required = false)
                       var customerId : String = "",
                       @field:Schema(description = "Delivery address to serve this order. By default it is filled with customer delivery default address",
                                         example = "" ,
                                        required = false)
                       var deliveryAdress : Address = Address(),
                       @field:Schema(description = "Invoice reference address used to fill corresponding invoice. By default is filled with default customer invoice address",
                                         example = "" ,
                                        required = false)
                       var invoiceAddress : Address = Address(),
                       @field:Schema(description = "Returning total base value for this order.",
                                         example = "371.26" ,
                                        required = false)
                       var baseValue : BigDecimal = BigDecimal(0),
                       @field:Schema(description = "Returning total vat value for this order.",
                                         example = "152.34" ,
                                        required = false)
                       var vatTaxValue : BigDecimal = BigDecimal(0),
                       @field:Schema(description = "Returning total alue for this order (tax included).",
                                         example = "523.60" ,
                                        required = false)
                       var totalValue : BigDecimal = BigDecimal(0),
                       @field:Schema(description = "Order Lines includind required items for this order.",
                                         example = "" ,
                                        required = true)
                       var lines : MutableList<OrderLine> = ArrayList()) {
}