apiVersion: v1
kind: ConfigMap
metadata:
  name: mqrabbit-reverse-proxy-config-map
  namespace: devel
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;
  
    events {
    }
  
    http {
    
      server {
          listen 80;     
          server_name churiservices.example;
          server_name_in_redirect on;
        
          location /rabbitmq/ {
              proxy_redirect off;
              proxy_pass http://rabbitmq-inner-service.devel.svc.cluster.local:15672/;  
              proxy_set_header Host $http_host;
              proxy_set_header X-Forwarded-Host $http_host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
                  
      }
      
    }