apiVersion: v1
kind: ConfigMap
metadata:
  name: mqrabbit-reverse-proxy-config-map
  namespace: devel
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;
  
    events {
    }
  
    http {
    
      server {
          listen 80;          
        
          location /rabbitmq/ {
              proxy_pass http://rabbitmq-inner-service.devel.svc.cluster.local:15672/;              
          }
                  
      }
      
    }