apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config-map
  namespace: devel
data:
  GF_PATHS_PROVISIONING: "/etc/grafana/provisioning"
  GF_AUTH_ANONYMOUS_ENABLED: "true"
  GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
