apiVersion: stackgres.io/v1
kind: SGPoolingConfig
metadata:
  namespace: {{ .Release.Namespace }}
  name: db-{{ .Chart.Name }}-{{ .Release.Name }}-poolconfig
spec:
  pgBouncer:
    pgbouncer.ini:
      pgbouncer:
        max_client_conn: {{ quote .Values.database.poolConf.pgBouncer.pgbouncerIni.pgbouncer.max_client_conn }}
        default_pool_size: {{ quote .Values.database.poolConf.pgBouncer.pgbouncerIni.pgbouncer.default_pool_size }}
        pool_mode: {{ quote .Values.database.poolConf.pgBouncer.pgbouncerIni.pgbouncer.pool_mode }}