apiVersion: stackgres.io/v1
kind: SGScript
metadata:
  namespace: {{ .Release.Namespace }}
  name: db-{{ .Chart.Name }}-{{ .Release.Name }}-scripts
spec:
  scripts:
    - name: create-db-{{ .Chart.Name }}-{{ .Release.Name }}-script
      scriptFrom:
        secretKeyRef:
          name: {{ .Chart.Name }}-{{ .Release.Name }}-secret
          key: create-database.sql